version: "3.9"

name: biocon-dev

services:
  database:
    image: postgres:16
    container_name: biocon-db
    restart: always
    user: root
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $SQL_DATABASE -U $SQL_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  db-data:
  uploads:
