version: "3.9"

name: biocon

services:
  database:
    image: postgres:16
    container_name: biocon-db
    restart: always
    networks:
      - nginx
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    tty: true
    stdin_open: true

  web:
    image: gosvoh/biocon:latest
    container_name: biocon-dev
    restart: always
    networks:
      - nginx
    volumes:
      - uploads:/app/uploads
    depends_on:
      - database
    environment:
      - DATABASE_URL
      - MAIL_USER
      - MAIL_PASS
      - TOPIC_ID
      - TELEGRAM_BOT_TOKEN
      - CHAT_ID
      - KEY
    tty: true
    stdin_open: true

networks:
  nginx:
    external: true

volumes:
  db-data:
  uploads:
