version: "3.9"

name: biocon

services:
  database:
    image: postgres:16
    container_name: biocon-db
    restart: always
    networks:
      - default
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  web:
    build: .
    container_name: biocon-dev
    restart: always
    networks:
      - default
      - nginx
    volumes:
      - uploads:/app/uploads
    depends_on:
      - database
    environment:
      - DATABASE_URL

networks:
  nginx:
    external: true

volumes:
  db-data:
  uploads:
